/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce.Mantenimiento;

import Bean.ClienteBean;
import Dao.ClienteDao;
import PlaceHolder.TextPrompt;
import e_comerce.Principal;
import static e_comerce.Principal.escritorio;
import e_comerce.Ubicacion;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;


import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.GenerarCodigoBarras;

import util.conexion;

/**
 *
 * @author Ralex
 */
public class ManCliente extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ClienteDao cDao = new ClienteDao();
    ClienteBean cBean = new ClienteBean();
    int rpt;

    public ManCliente() {
        initComponents();
        modelo.addColumn("RucCliente");
        modelo.addColumn("NombreRazon");
        modelo.addColumn("CreditoContado");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ubigeo");
        modelo.addColumn("Distrito");
        modelo.addColumn("Provincia");
        modelo.addColumn("Departamento");
        modelo.addColumn("Telefono");
        modelo.addColumn("TelefonoWsp");
        modelo.addColumn("Fax");
        modelo.addColumn("ContactoAdmi");
        modelo.addColumn("TelefonoAdmi");
        modelo.addColumn("ContactoVentas");
        modelo.addColumn("TelefonoVentas");
        modelo.addColumn("RetornoDocumento");
        modelo.addColumn("Activacion");
        modelo.addColumn("TipoCliente");
        modelo.addColumn("Confirma");
        modelo.addColumn("Corp");
        tblmancliente.setModel(modelo);
        cDao.listarClienteMantenimiento(txtBuscarMantClientes.getText());
        combox();
        placeholder();
    }

    
    void combox(){
        if (cbCreditoContado.getSelectedItem().equals("C")) {
            lblcbRC.setText("Contado");
        }else if (cbCreditoContado.getSelectedItem().equals("R")) {
            lblcbRC.setText("Credito");
        }else{
            lblcbRC.setText("Seleccione");
        }
        
    }
    
    void placeholder(){
        TextPrompt txt1 = new TextPrompt("Ejmp: 123456789101", txtRucCliente);
        TextPrompt txt2 = new TextPrompt("Ejmp: RazonSocial..", txtRznSocial);
        TextPrompt txt3 = new TextPrompt("Ejmp: San Juan Miraflores Mz k1 lote 6 la rinconada", txtDireccion);
        TextPrompt txt4 = new TextPrompt("Ejmp: 123456789", txtTelefono);
        TextPrompt txt5 = new TextPrompt("Ejmp: 123456789", txtTelefonoWsp);
        TextPrompt txt6 = new TextPrompt("Ejmp: 123456789", txtFax);
        
        
        TextPrompt txt7 = new TextPrompt("Ejmp: Contacto Administrado", txtContacAdm);            
        TextPrompt txt8 = new TextPrompt("Ejmp: 123456789", txtTelefonoAdm);
        TextPrompt txt9 = new TextPrompt("Ejmp: Contacto de Ventas", txtContacVentas);
        TextPrompt txt10 = new TextPrompt("Ejmp: 123456789", txtTelefonoVentas);
        
        
        TextPrompt txt11 = new TextPrompt("Nombre o Ruc", txtBuscarMantClientes);
        
        
        
    }
    
    void Limpiar(){
        txtRucCliente.setText("");
        txtRznSocial.setText("");
        cbCreditoContado.setSelectedIndex(0);
        txtDireccion.setText("");
        combox();
        lblUbigeo.setText("");
        lblNomUbigeo.setText("<- Ingrese Su Ubigeo");
        txtTelefono.setText("");
        txtTelefonoWsp.setText("");
        txtFax.setText("");
        txtContacAdm.setText("");
        txtTelefonoAdm.setText("");
        txtContacVentas.setText("");
        txtTelefonoVentas.setText("");
        cbRetornoDoc.setSelectedIndex(0);
        cbActivacion.setSelectedIndex(0);
        cbTipoCliente.setSelectedIndex(0);
        cbConfirma.setSelectedIndex(0);
        cbCorp.setSelectedIndex(0);
        placeholder();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRucCliente = new javax.swing.JTextField();
        txtRznSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtTelefonoWsp = new javax.swing.JTextField();
        cbCreditoContado = new javax.swing.JComboBox<>();
        lblUbigeo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        lblcbRC = new javax.swing.JLabel();
        lblNomUbigeo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtContacAdm = new javax.swing.JTextField();
        txtTelefonoAdm = new javax.swing.JTextField();
        txtContacVentas = new javax.swing.JTextField();
        txtTelefonoVentas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbActivacion = new javax.swing.JComboBox<>();
        cbRetornoDoc = new javax.swing.JComboBox<>();
        cbTipoCliente = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbConfirma = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbCorp = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtBuscarMantClientes = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmancliente = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cliente"));

        jLabel1.setText("Ruc Cliente:");

        jLabel2.setText("Razon Social :");

        jLabel3.setText("Credito/Contado :");

        jLabel4.setText("Direccion :");

        jLabel5.setText("Ubigeo :");

        jLabel6.setText("Telefono :");

        jLabel7.setText("TelefonoWahtsap :");

        cbCreditoContado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "R", "C" }));
        cbCreditoContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCreditoContadoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgButton/ubicacionclara.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgButton/ubicacion.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fax :");

        lblNomUbigeo.setText("<- Ingrese Su Ubigeo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUbigeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoWsp)
                                    .addComponent(txtFax)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomUbigeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCreditoContado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcbRC, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtRznSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRznSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcbRC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbCreditoContado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUbigeo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNomUbigeo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoWsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Otros Contactos"));

        jLabel9.setText("C.Admiistrador :");

        jLabel10.setText("Telefono Admi  :");

        jLabel11.setText("Contacto Ventas :");

        jLabel12.setText("Telefono Ventas :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtContacAdm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoAdm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefonoVentas)
                            .addComponent(txtContacVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtContacAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelefonoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtContacVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTelefonoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adjunto"));

        jLabel13.setText("Retorno Documento :");

        jLabel14.setText("Activacion :");

        jLabel15.setText("Tipo Cliente :");

        cbActivacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "N" }));

        cbRetornoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        cbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N", "J" }));

        jLabel16.setText("Confirma :");

        cbConfirma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel17.setText("Corp :");

        cbCorp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cbCorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCorpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbRetornoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbActivacion, 0, 60, Short.MAX_VALUE)
                            .addComponent(cbTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbConfirma, 0, 60, Short.MAX_VALUE)
                            .addComponent(cbCorp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbRetornoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbActivacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cbCorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Operaciones"));

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel18.setText("Buscar :");

        txtBuscarMantClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarMantClientesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarMantClientesKeyReleased(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscarMantClientes))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel18)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addGap(11, 11, 11)
                .addComponent(btnEliminar)
                .addGap(33, 33, 33)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarMantClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        tblmancliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmancliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblmancliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmancliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Ubicacion u;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Principal.estacerrado(u)) {
            u = new Ubicacion();
            escritorio.add(u).setLocation(250, 300);
            u.cbEnviar.setSelectedItem("Enviar a Clientes");
            u.toFront();
            u.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "La ventana Ubigeo\n ya esta abierta !!!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarMantClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMantClientesKeyReleased
        cDao.listarClienteMantenimiento(txtBuscarMantClientes.getText().toString());
    }//GEN-LAST:event_txtBuscarMantClientesKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rpt = JOptionPane.showConfirmDialog(null, "Seguro que desea registrar?");

        if (rpt == JOptionPane.YES_OPTION) {
            cBean.setRucCliente(txtRucCliente.getText());
            cBean.setNombreRazon(txtRznSocial.getText());
            cBean.setCreditoContado(cbCreditoContado.getSelectedItem().toString());
            cBean.setDireccion(txtDireccion.getText());
            cBean.setUbigeo(lblUbigeo.getText().toString());
            cBean.setTelefono(Integer.parseInt(txtTelefono.getText()));
            cBean.setTelefonoWsp(Integer.parseInt(txtTelefonoWsp.getText()));
            cBean.setFax(txtFax.getText());
            cBean.setContactoAdmi(txtContacAdm.getText());
            cBean.setTelefonoAdmi(Integer.parseInt(txtTelefonoAdm.getText()));
            cBean.setContactoVentas(txtContacVentas.getText());
            cBean.setTelefonoVentas(Integer.parseInt(txtTelefonoVentas.getText()));
            cBean.setRetornoDocumento(cbRetornoDoc.getSelectedItem().toString());
            cBean.setActivacion(cbActivacion.getSelectedItem().toString());
            cBean.setTipoCliente(cbTipoCliente.getSelectedItem().toString());
            cBean.setConfirma(cbConfirma.getSelectedItem().toString());
            cBean.setCorp(cbCorp.getSelectedItem().toString());

            cDao.registrarAgente(cBean);
            cDao.listarClienteMantenimiento(txtBuscarMantClientes.getText());
            
            
            
            Limpiar();
        } else if (rpt == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "No se realizo ningun registro!");
        } else if (rpt == JOptionPane.CANCEL_OPTION) {

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbCorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCorpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCorpActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        rpt = JOptionPane.showConfirmDialog(null, "Seguro que desea Actualizar?");

        if (rpt == JOptionPane.YES_OPTION) {
            cBean.setNombreRazon(txtRznSocial.getText());
            cBean.setCreditoContado(cbCreditoContado.getSelectedItem().toString());
            cBean.setDireccion(txtDireccion.getText());
            cBean.setUbigeo(lblUbigeo.getText().toString());
            cBean.setTelefono(Integer.parseInt(txtTelefono.getText()));
            cBean.setTelefonoWsp(Integer.parseInt(txtTelefonoWsp.getText()));
            cBean.setFax(txtFax.getText());
            cBean.setContactoAdmi(txtContacAdm.getText());
            cBean.setTelefonoAdmi(Integer.parseInt(txtTelefonoAdm.getText()));
            cBean.setContactoVentas(txtContacVentas.getText());
            cBean.setTelefonoVentas(Integer.parseInt(txtTelefonoVentas.getText()));
            cBean.setRetornoDocumento(cbRetornoDoc.getSelectedItem().toString());
            cBean.setActivacion(cbActivacion.getSelectedItem().toString());
            cBean.setTipoCliente(cbTipoCliente.getSelectedItem().toString());
            cBean.setConfirma(cbConfirma.getSelectedItem().toString());
            cBean.setCorp(cbCorp.getSelectedItem().toString());
            cBean.setRucCliente(txtRucCliente.getText());

            cDao.actualizarCliente(cBean);
            cDao.listarClienteMantenimiento(txtBuscarMantClientes.getText());
            
            Limpiar();
        } else if (rpt == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "No se realizo ninguna actualizacion");
        } else if (rpt == JOptionPane.CANCEL_OPTION) {

        }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tblmanclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanclienteMouseClicked
        for (int i = 0; i < tblmancliente.getRowCount(); i++) {
            int fila = tblmancliente.getSelectedRow();
            txtRucCliente.setText(tblmancliente.getValueAt(fila, 0).toString());
            
            txtBuscarMantClientes.setText(tblmancliente.getValueAt(fila, 0).toString());
            
            txtRznSocial.setText(tblmancliente.getValueAt(fila, 1).toString());
            cbCreditoContado.setSelectedItem(tblmancliente.getValueAt(fila, 2).toString());
            txtDireccion.setText(tblmancliente.getValueAt(fila, 3).toString());
            lblUbigeo.setText(tblmancliente.getValueAt(fila, 4).toString());
            
            String nombre = null;
                String dis = tblmancliente.getValueAt(fila, 5).toString();
                String pro = tblmancliente.getValueAt(fila, 6).toString();
                String dep = tblmancliente.getValueAt(fila, 7).toString();
                nombre = dis + ' ' + pro + ' ' + dep;                
            lblNomUbigeo.setText(nombre);
            
            
            txtTelefono.setText(tblmancliente.getValueAt(fila, 8).toString());
            txtTelefonoWsp.setText(tblmancliente.getValueAt(fila, 9).toString());
            txtFax.setText(tblmancliente.getValueAt(fila, 10).toString());
            txtContacAdm.setText(tblmancliente.getValueAt(fila, 11).toString());
            txtTelefonoAdm.setText(tblmancliente.getValueAt(fila, 12).toString());
            txtContacVentas.setText(tblmancliente.getValueAt(fila, 13).toString());
            txtTelefonoVentas.setText(tblmancliente.getValueAt(fila, 14).toString());
            cbRetornoDoc.setSelectedItem(tblmancliente.getValueAt(fila, 15).toString());
            cbActivacion.setSelectedItem(tblmancliente.getValueAt(fila, 16).toString());
            cbTipoCliente.setSelectedItem(tblmancliente.getValueAt(fila, 17).toString());
            cbConfirma.setSelectedItem(tblmancliente.getValueAt(fila, 18).toString());
            cbCorp.setSelectedItem(tblmancliente.getValueAt(fila, 19).toString());
        }
    }//GEN-LAST:event_tblmanclienteMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        rpt = JOptionPane.showConfirmDialog(null, "Seguro que desea Eliminar?");

        if (rpt == JOptionPane.YES_OPTION) {
            cDao.eliminarCliente(txtRucCliente.getText());
            cDao.listarClienteMantenimiento(txtBuscarMantClientes.getText());
            
            Limpiar();
        } else if (rpt == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "No se a realizado ningun cambio");
        } else if (rpt == JOptionPane.CANCEL_OPTION) {

        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbCreditoContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCreditoContadoActionPerformed
        combox();
    }//GEN-LAST:event_cbCreditoContadoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarMantClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarMantClientesKeyPressed
        GenerarCodigoBarras g = new GenerarCodigoBarras();
        
        String bar = "";
        bar = txtBuscarMantClientes.getText();
        System.err.println(bar);
        g.barras(bar,txtRznSocial.getText(),txtDireccion.getText(),bar);
         
            
    }//GEN-LAST:event_txtBuscarMantClientesKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbActivacion;
    private javax.swing.JComboBox<String> cbConfirma;
    private javax.swing.JComboBox<String> cbCorp;
    private javax.swing.JComboBox<String> cbCreditoContado;
    private javax.swing.JComboBox<String> cbRetornoDoc;
    private javax.swing.JComboBox<String> cbTipoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblNomUbigeo;
    public static javax.swing.JLabel lblUbigeo;
    private javax.swing.JLabel lblcbRC;
    public static javax.swing.JTable tblmancliente;
    private javax.swing.JTextField txtBuscarMantClientes;
    private javax.swing.JTextField txtContacAdm;
    private javax.swing.JTextField txtContacVentas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtRucCliente;
    private javax.swing.JTextField txtRznSocial;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoAdm;
    private javax.swing.JTextField txtTelefonoVentas;
    private javax.swing.JTextField txtTelefonoWsp;
    // End of variables declaration//GEN-END:variables
}
