/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce;

import Dao.AgentesDao;
import PlaceHolder.TextPrompt;
import e_comerce.Mantenimiento.MantCentroCostos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralex
 */
public class Aagente extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    AgentesDao ad = new AgentesDao();
    
    public Aagente() {
        initComponents();
        modelo.addColumn("RucAgente");
        modelo.addColumn("Tipo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("TelefonoCell");
        modelo.addColumn("TelefonoWsp");
        modelo.addColumn("RucCliente");
        modelo.addColumn("Fax");
        modelo.addColumn("Ubigeo");
        modelo.addColumn("Distrito");
        modelo.addColumn("Provincia");
        modelo.addColumn("Departamento");
        modelo.addColumn("Email");
        modelo.addColumn("PagoTransporte");
        modelo.addColumn("KgBasRep");
        modelo.addColumn("KgAdicional");
        modelo.addColumn("LPorcMontoCCorto");
        modelo.addColumn("LBasicoCCorto");
        modelo.addColumn("LAdicionalCCorto");
        modelo.addColumn("LPorcMontoCLargo");
        modelo.addColumn("LBasicoCLargo");
        modelo.addColumn("LAdicionalCLargo");
        modelo.addColumn("SPorcMontoCCorto");
        modelo.addColumn("SBasicoCCorto");
        modelo.addColumn("SAdicionalCCorto");
        modelo.addColumn("SPorcMontoCLargo");
        modelo.addColumn("SBasicoCLargo");
        modelo.addColumn("SAdicionalCLargo");        
        tblAagentes.setModel(modelo);        
        ad.listarAgentes(txtBuscarAagente.getText());
        placeholder();
    }

    void placeholder(){
        
        TextPrompt txt1 = new TextPrompt("Ingrese Ruc, Nombre, Ubigeo, Distrito, Provincia o Departamento", txtBuscarAagente);
        
               
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAagentes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarAagente = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        tblAagentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAagentes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblAagentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAagentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAagentes);

        jLabel1.setText("Agentes :");

        txtBuscarAagente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarAagenteKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione envio", "Enviar a Centro Costo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarAagente, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarAagente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //        if (isSelected == jComboBox1.getSelectedItem().equals("Enviar a Centro Costo")) {
            //            for (int i = 0; i < tblAgentes.getRowCount(); i++) {
                //            int fila = tblAgentes.getSelectedRow();
                //                MantCentroCostos.lblAgen.setText(tblAgentes.getValueAt(fila, 0).toString());
                //        }
            //        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtBuscarAagenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarAagenteKeyReleased
        AgentesDao ad = new AgentesDao();
        ad.listarAgentes(txtBuscarAagente.getText());
    }//GEN-LAST:event_txtBuscarAagenteKeyReleased

    private void tblAagentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAagentesMouseClicked
        if (isSelected == jComboBox1.getSelectedItem().equals("Enviar a Centro Costo")) {
            for (int i = 0; i < tblAagentes.getRowCount(); i++) {
                int fila = tblAagentes.getSelectedRow();
                MantCentroCostos.lblAgen.setText(tblAagentes.getValueAt(fila, 0).toString());
                
                MantCentroCostos.lblnomAgente.setText(tblAagentes.getValueAt(fila, 2).toString());                
                
            }
        }
    }//GEN-LAST:event_tblAagentesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblAagentes;
    private javax.swing.JTextField txtBuscarAagente;
    // End of variables declaration//GEN-END:variables
}
