/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce;

import Dao.ClienteDao;
import PlaceHolder.TextPrompt;
import e_comerce.Mantenimiento.ManAgente;
import static e_comerce.Mantenimiento.ManAgente.cbClienteono;
import e_comerce.Mantenimiento.ManCliente;
import e_comerce.Mantenimiento.ManTarifas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralex
 */
public class Clientes extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    ClienteDao cdao = new ClienteDao();

    public Clientes() {
        initComponents();
        modelo.addColumn("RucCliente");
        modelo.addColumn("NombreRazon");
        modelo.addColumn("CreditoContado");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ubigeo");
        modelo.addColumn("Distrito");
        modelo.addColumn("Provincia");
        modelo.addColumn("Departamento");
        modelo.addColumn("Telefono");
        modelo.addColumn("TelefonoWsp");
        modelo.addColumn("Fax");
        modelo.addColumn("ContactoAdmi");
        modelo.addColumn("TelefonoAdmi");
        modelo.addColumn("ContactoVentas");
        modelo.addColumn("TelefonoVentas");
        modelo.addColumn("RetornoDocumento");
        modelo.addColumn("Activacion");
        modelo.addColumn("TipoCliente");
        modelo.addColumn("Confirma");
        modelo.addColumn("Corp");
        tblClientes.setModel(modelo);
        cdao.listarCliente(txtbuscarC.getText());
        placeholder();

    }
    void placeholder(){
        TextPrompt txt1 = new TextPrompt("Ejmp: Ruc, Nombre, Ubigeo, Distrito, Provincia, Departamento", txtbuscarC);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtbuscarC = new javax.swing.JTextField();
        cbClientes = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Clientes");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setText("Clientes");

        txtbuscarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuscarCMousePressed(evt);
            }
        });
        txtbuscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarCKeyReleased(evt);
            }
        });

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione envio", "Enviar a Agentes", "Enviar a Tarifas" }));
        cbClientes.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuscarCMousePressed

    }//GEN-LAST:event_txtbuscarCMousePressed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        if (isSelected == cbClientes.getSelectedItem().equals("Enviar a Agentes")) {
            for (int i = 0; i < tblClientes.getRowCount(); i++) {
                int fila = tblClientes.getSelectedRow();

                String enviar = null;
                String cod = tblClientes.getValueAt(fila, 0).toString();
                String nom = tblClientes.getValueAt(fila, 1).toString();
                enviar = cod + '-' + nom;
                ManAgente.lblRucCliente.setText(enviar);
                ManAgente.cbClienteono.setSelectedIndex(1);
            }
        } else if (isSelected == cbClientes.getSelectedItem().equals("Enviar a Tarifas")) {
            for (int i = 0; i < tblClientes.getRowCount(); i++) {
                int fila = tblClientes.getSelectedRow();

                String ruc = tblClientes.getValueAt(fila, 0).toString();
                String nom = tblClientes.getValueAt(fila, 1).toString();

                ManTarifas.lblRuc.setText(ruc);
                ManTarifas.lblNombre.setText(nom);

            }
        }


    }//GEN-LAST:event_tblClientesMouseClicked

    ClienteDao cd = new ClienteDao();
    private void txtbuscarCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarCKeyReleased
        cd.listarCliente(txtbuscarC.getText());
    }//GEN-LAST:event_txtbuscarCKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblClientes;
    public static javax.swing.JTextField txtbuscarC;
    // End of variables declaration//GEN-END:variables
}
