/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce;

import Dao.PorcionTerrestreDao;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralex
 */
public class PorcionTerrestre extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    PorcionTerrestreDao ptDao = new PorcionTerrestreDao();
    
    
    public PorcionTerrestre() {
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Ubigeo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("RegionLocal");
        modelo.addColumn("PorcenMonto");
        modelo.addColumn("importe");
        modelo.addColumn("Observacion");
        modelo.addColumn("MontoComAGT");
        tblPorcionTerrestre.setModel(modelo);
        ptDao.Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPorcionTerrestre = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPT = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Porcion Terrestre");
        setToolTipText("");

        tblPorcionTerrestre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPorcionTerrestre);

        jLabel1.setText("Porcion Terrestre");

        txtBuscarPT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPTKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarPT, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarPTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPTKeyReleased
        ptDao.listarPT(txtBuscarPT.getText());
    }//GEN-LAST:event_txtBuscarPTKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblPorcionTerrestre;
    private javax.swing.JTextField txtBuscarPT;
    // End of variables declaration//GEN-END:variables
}
