/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce;

import Bean.TarifasBean;
import Dao.TarifasDao;
import e_comerce.Transacciones.Ordenes;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralex
 */
public class Tarifas extends javax.swing.JInternalFrame {

    TarifasBean  tb = new TarifasBean();
    TarifasDao td = new TarifasDao();
    DefaultTableModel modelo = new DefaultTableModel();
    
    
    public Tarifas() {
        initComponents();
        modelo.addColumn("Codigo");
        modelo.addColumn("Tipo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("RucCliente");
        modelo.addColumn("Nombre");
        modelo.addColumn("C.Origen");
        modelo.addColumn("Nom.Origen");
        modelo.addColumn("C.Destino");
        modelo.addColumn("Nom.Destino");
        modelo.addColumn("P.T.Origen");
        modelo.addColumn("P.T.Destino");
        modelo.addColumn("KilajeMin.");
        modelo.addColumn("Recojo");
        modelo.addColumn("Prioridad");
        modelo.addColumn("Valorado");
        modelo.addColumn("Embalaje");
        modelo.addColumn("Tarf.Local");
        modelo.addColumn("ZonaAlejada");
        modelo.addColumn("KgLocal");
        modelo.addColumn("TarifaB.T");
        modelo.addColumn("TarifaB.A");
        modelo.addColumn("SobrePesoT.");
        modelo.addColumn("SobrePesoA.");
        modelo.addColumn("PesoVol.T");
        modelo.addColumn("PesoVol.A");
        modelo.addColumn("TransbordoT.");
        modelo.addColumn("Trans.Adic.T");
        modelo.addColumn("TransbordoA.");
        modelo.addColumn("Trans.Adic.T");
        tblTarifas.setModel(modelo);
        td.listarTarifas(txtBuscar.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTarifas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        tblTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTarifas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblTarifas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTarifasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTarifas);

        jLabel1.setText("Buscar :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(830, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
       td.listarTarifas(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblTarifasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTarifasMouseClicked
        for (int i = 0; i < tblTarifas.getRowCount(); i++) {
            int fila = tblTarifas.getSelectedRow();
            Ordenes.lblNomOrigen1.setText(tblTarifas.getValueAt(fila, 4).toString());        
            Ordenes.lblRucCliente.setText(tblTarifas.getValueAt(fila, 3).toString());
            //tarifa basica
            Ordenes.lblTarifaBasicaT.setText(tblTarifas.getValueAt(fila, 17).toString());
            Ordenes.lblTarifaBasicaA.setText(tblTarifas.getValueAt(fila, 18).toString());
            //sobrepeso
            Ordenes.lblSobrepesoT.setText(tblTarifas.getValueAt(fila, 19).toString());
            Ordenes.lblSobrePesoA.setText(tblTarifas.getValueAt(fila, 20).toString());
            //PesoVolumen
            Ordenes.lblPesoVolumenT.setText(tblTarifas.getValueAt(fila, 21).toString());
            Ordenes.lblPesoVolumenA.setText(tblTarifas.getValueAt(fila, 22).toString());
            //Transbordo Terrestre
            Ordenes.lblTransbordoT.setText(tblTarifas.getValueAt(fila, 23).toString());
            Ordenes.lblAdicionalTransbordoT1.setText(tblTarifas.getValueAt(fila, 24).toString());
            //Transbordo Aereo
            Ordenes.lblTransbordoA.setText(tblTarifas.getValueAt(fila, 25).toString());
            Ordenes.lblAdicionalTransbordoA.setText(tblTarifas.getValueAt(fila, 26).toString());
            
            //KilajeMinimo
            Ordenes.lblKilajeMinimo.setText(tblTarifas.getValueAt(fila, 11).toString());
            
            //Recojo
            Ordenes.lblRecojo.setText(tblTarifas.getValueAt(fila, 12).toString());
            //Prioridad
            Ordenes.lblPrioridad.setText(tblTarifas.getValueAt(fila, 13).toString());
            //Valorado
            Ordenes.lblValorado.setText(tblTarifas.getValueAt(fila, 14).toString());
            Ordenes.lblEmbalaje.setText(tblTarifas.getValueAt(fila, 15).toString());
        }
    }//GEN-LAST:event_tblTarifasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblTarifas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
