/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e_comerce;

import Bean.UbicacionBean;
import Dao.UbicacionDao;
import e_comerce.Mantenimiento.ManAgente;
import e_comerce.Mantenimiento.ManCliente;
import e_comerce.Mantenimiento.ManPorcionTerrestre;
import e_comerce.Mantenimiento.ManRutas;
import e_comerce.Mantenimiento.MantCentroCostos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralex
 */
public class Ubicacion extends javax.swing.JInternalFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    UbicacionDao udao = new UbicacionDao();
    UbicacionBean ubean = new UbicacionBean();

    public Ubicacion() {
        initComponents();
        modelo.addColumn("Ubigeo");
        modelo.addColumn("Distrito");
        modelo.addColumn("Provincia");
        modelo.addColumn("Departamento");
        modelo.addColumn("Establecimiento");
        tblUbicacion.setModel(modelo);
        udao.Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUbicacion = new javax.swing.JTable();
        txtBuscarUbigeo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbEnviar = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Ubicacion");

        tblUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUbicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUbicacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUbicacion);

        txtBuscarUbigeo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUbigeoKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar X Ubigeo");

        cbEnviar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione envio", "Enviar a Clientes", "Enviar a Agentes", "Enviar a Centro Costo", "Enviar a Ruta Origen", "Enviar a Ruta Destino", "Enviar a Porcion Terrestre" }));
        cbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(txtBuscarUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUbigeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarUbigeoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUbigeoKeyReleased

        udao.listarUbicacion(txtBuscarUbigeo.getText().toString());
    }//GEN-LAST:event_txtBuscarUbigeoKeyReleased

    private void tblUbicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUbicacionMouseClicked
        /*for (int i = 0; i < tblUbicacion.getRowCount(); i++) {
            int fila = tblUbicacion.getSelectedRow();
            ManCliente.lblUbigeo.setText(tblUbicacion.getValueAt(fila, 0).toString());
             ManAgente.lblUbigeo.setText(tblUbicacion.getValueAt(fila, 0).toString());

        }*/
        if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Clientes")) {
            for (int i = 0; i < tblUbicacion.getRowCount(); i++) {
                int fila = tblUbicacion.getSelectedRow();
                ManCliente.lblUbigeo.setText(tblUbicacion.getValueAt(fila, 0).toString());

            }
        } else if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Agentes")) {
            for (int i = 0; i < tblUbicacion.getRowCount(); i++) {
                int fila = tblUbicacion.getSelectedRow();
                ManAgente.lblUbigeo.setText(tblUbicacion.getValueAt(fila, 0).toString());
                
                String nombre = null;
                String dis = tblUbicacion.getValueAt(fila, 1).toString();
                String pro = tblUbicacion.getValueAt(fila, 2).toString();
                String dep = tblUbicacion.getValueAt(fila, 3).toString();
                nombre = dis + ' ' + pro + ' ' + dep;
                ManAgente.lblNombreUbi.setText(nombre);

            }
        } else if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Centro Costo")) {
            for (int i = 0; i < tblUbicacion.getRowCount(); i++) {
                int fila = tblUbicacion.getSelectedRow();
                MantCentroCostos.lblUbi.setText(tblUbicacion.getValueAt(fila, 0).toString());
                String nombre = null;
                String dis = tblUbicacion.getValueAt(fila, 1).toString();
                String pro = tblUbicacion.getValueAt(fila, 2).toString();
                String dep = tblUbicacion.getValueAt(fila, 3).toString();
                nombre = dis + ' ' + pro + ' ' + dep;
                MantCentroCostos.lblnomUbigeo.setText(nombre);
            }
        } else if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Ruta Origen")) {
            for (int i = 0; i < tblUbicacion.getRowCount(); i++) {

                int fila = tblUbicacion.getSelectedRow();
                ManRutas.lblCO.setText(tblUbicacion.getValueAt(fila, 0).toString());
                String nombre = null;
                String dep = tblUbicacion.getValueAt(fila, 1).toString();
                String pro = tblUbicacion.getValueAt(fila, 2).toString();
                String dis = tblUbicacion.getValueAt(fila, 3).toString();
                nombre = dep + ' ' + pro + ' ' + dis;

                ManRutas.lblNomCO.setText(nombre);

            }
        } else if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Ruta Destino")) {
            int fila = tblUbicacion.getSelectedRow();
            ManRutas.lblCD.setText(tblUbicacion.getValueAt(fila, 0).toString());

            String nombre = null;
            String dep = tblUbicacion.getValueAt(fila, 1).toString();
            String pro = tblUbicacion.getValueAt(fila, 2).toString();
            String dis = tblUbicacion.getValueAt(fila, 3).toString();
            nombre = dep + ' ' + pro + ' ' + dis;

            ManRutas.lblNomCD.setText(nombre);

        }else if (isSelected == cbEnviar.getSelectedItem().equals("Enviar a Porcion Terrestre")) {
            int fila = tblUbicacion.getSelectedRow();
            ManPorcionTerrestre.lblUbigeo.setText(tblUbicacion.getValueAt(fila, 0).toString());
            
            String nombre = null;
            String dep = tblUbicacion.getValueAt(fila, 1).toString();
            String pro = tblUbicacion.getValueAt(fila, 2).toString();
            String dis = tblUbicacion.getValueAt(fila, 3).toString();
            nombre = dep + ' ' + pro + ' ' + dis;

            ManPorcionTerrestre.txtDescripcion.setText(nombre);
        }
            
    }//GEN-LAST:event_tblUbicacionMouseClicked

    private void cbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnviarActionPerformed

    }//GEN-LAST:event_cbEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblUbicacion;
    private javax.swing.JTextField txtBuscarUbigeo;
    // End of variables declaration//GEN-END:variables
}
